name: Integración Continua con Maven

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Validate project
        run: mvn validate --file pom.xml --quiet

      - name: Compile project
        run: mvn compile --file pom.xml --quiet

      - name: Run tests
        run: mvn test --file pom.xml --quiet

      - name: Package project
        run: mvn package --file pom.xml --quiet
